=== sandesh352/3rd-sem-labreport-web/xml/message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
 xmlns:xsi="https://www.anydomain.com" elementFormDefault="qualified">
  <xs:element name="message">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="to" type="xs:string"/>
        <xs:element name="from" type="xs:string"/>
        <xs:element name="heading" type="xs:string"/>
        <xs:element name="country">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:enumeration value="usa"/>
<xs:enumeration value="aus"/>
<xs:enumeration value="jap"/>
</xs:restriction>
</xs:simpleType>        
        </xs:element>
        
    <xs:element name="age">
      <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="10"/>
            <xs:maxInclusive value="120"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>        
        
        <xs:element name="body">
              <xs:complexType>
              <xs:sequence>
              <xs:element name="info" type="xs:string"/>
              </xs:sequence>
                 <xs:attribute name="lang" type="xs:string"/>          
              </xs:complexType>
              </xs:element>
              
              <xs:element name="password">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9]{8}"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
              
              
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sandesh352/3rd-sem-labreport-web/xml/message.xml
<?xml version="1.0" encoding="UTF-8"?>
<message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
xsi:noNamespaceSchemaLocation ="message.xsd">
<to>Nishan</to>
<from>Uchit noob</from>
<heading>Request</heading>
<country>usa</country>
<age>11</age>
<body lang="en">
<info>please help</info>
</body>
<password>ihwj2uid</password>
</message>
